lds_revolute:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  # Position Controllers ---------------------------------------
  lds_revolute_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: lds_revolute
    pid: {p: 10.0, i: 0.1, d: 1.0}
